# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pg_scope_by_soundex}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alejandro Juarez"]
  s.date = %q{2010-06-01}
  s.description = %q{The pg_scope_by_soundex gem uses the set of functions of contrib/fuzzystringmatching for PostgreSQL.}
  s.email = %q{alex@monsterlabs.com.mx}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "init.rb",
     "lib/generators/pg_scope_by_soundex_install/USAGE",
     "lib/generators/pg_scope_by_soundex_install/pg_scope_by_soundex_install_generator.rb",
     "lib/generators/pg_scope_by_soundex_install/templates/migration.rb",
     "lib/pg_scope_by_soundex.rb",
     "lib/pg_scope_by_soundex/named_scope.rb"
  ]
  s.homepage = %q{http://github.com/alecz/pg_scope_by_soundex}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{This gem provides the soundex and difference postgresql functions to determine similarities and distance between strings}
  s.test_files = [
    "spec/fuzzy_string_matcher_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

